baseURL = 'https://test.mcelwain.me/'
defaultContentLanguage = "en"
languageCode = "en-us"

title = 'Connor McElwain'
theme = 'gokarna'

[params]
  avatarURL = "/images/logos/"
  description = "DESC"
  ShowBackToTopButton = true
  metaKeywords = ["blog", "gokarna", "hugo"]

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false


[menu]
  [[menu.main]]
    identifier = "Home"
    url = "https://test.mcelwain.me"
    name = "Home"
    pre = "<span data-feather='home'></span>"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    url = "/tags/"
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
    [[menu.main]]
    identifier = "test"
    name = "Test"
    url = "test/"
    weight = 5
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/ConnorMcElwain"
    weight = 6
    pre = "<span data-feather='github'></span>"
